[+ AutoGen5 template h c +]
[+ CASE (suffix) +][+
   ==  h  +]#ifndef LIST_H
#define LIST_H

[+ (lgpl "test_package" "conan-io-center" "// ") +]

typedef enum {[+
   FOR list "," +]
        IDX_[+ (string-upcase! (get "list_element")) +][+
   ENDFOR list +] }  list_enum;

extern char const* az_name_list[ [+ (count "list") +] ];

// Generated by AutoGen [+ (emit autogen-version) +]

#endif // LIST_H
[+

   ==  c  +]
[+  (lgpl "test_package" "conan-io-center" "// ") +]

#include "list.h"

char const* az_name_list[] = {[+
  FOR list "," +]
        "[+list_info+]"[+
  ENDFOR list +] };

// Generated by AutoGen [+ (emit autogen-version) +]
[+

ESAC +]
